services:
  # Backend API Service
  - type: web
    name: ai-quiz-backend
    runtime: python
    buildCommand: pip install --only-binary=:all: -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: PIP_ONLY_BINARY
        value: ":all:"
    healthCheckPath: /health

  # Frontend Service
  - type: web
    name: ai-quiz-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: ai-quiz-backend
          property: url
